In [1]:
print("ss")


ss


In [4]:
import tensorflow as tf
a = tf.constant([1.0,2.0])
b = tf.constant([3.0,4.0])
c = tf.multiply(a,b)
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(c))
    print(c.eval())
    



[3. 8.]
[3. 8.]


In [22]:
state = tf.Variable(0,name = "counter")
input1 = tf.constant(3.0)
input1 = tf.placeholder(tf.float32)
input2 = tf.placeholder(tf.float32)
output = tf.multiply(input1,input2)
with tf.Session() as sess:
    print(sess.run(output,feed_dict={input1:7.0,input2:2.0}))
    

14.0


In [7]:
from __future__ import print_function,division
import tensorflow as tf

#build a graph
print("build a graph")
a=tf.constant([[1,2],[3,4]])
b=tf.constant([[1,1],[0,1]])
print("a:",a)
print("b:",b)
print("type of a:",type(a))
c=tf.matmul(a,b)
print("c:",c)
print("\n")
#construct a 'Session' to excute the graph
sess=tf.Session()

# Execute the graph and store the value that `c` represents in `result`.
print("excuted in Session")
result_a=sess.run(a)
result_a2=a.eval(session=sess)
print("result_a:\n",result_a)
print("result_a2:\n",result_a2)

result_b=sess.run(b)
print("result_b:\n",result_b)

result_c=sess.run(c)
print("result_c:\n",result_c)

build a graph
a: Tensor("Const_7:0", shape=(2, 2), dtype=int32)
b: Tensor("Const_8:0", shape=(2, 2), dtype=int32)
type of a: <class 'tensorflow.python.framework.ops.Tensor'>
c: Tensor("MatMul_1:0", shape=(2, 2), dtype=int32)


excuted in Session
result_a:
 [[1 2]
 [3 4]]
result_a2:
 [[1 2]
 [3 4]]
result_b:
 [[1 1]
 [0 1]]
result_c:
 [[1 3]
 [3 7]]


In [10]:
c = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
print(c.get_shape())
# ==> TensorShape([Dimension(2), Dimension(3)])

d = tf.constant([[1.0, 0.0], [0.0, 1.0], [1.0, 0.0], [0.0, 1.0]])
print(d.get_shape())
# ==> TensorShape([Dimension(4), Dimension(2)])

# Raises a ValueError, because `c` and `d` do not have compatible
# inner dimensions.
# e = tf.matmul(c, d)
# 
# f = tf.matmul(c, d, transpose_a=True, transpose_b=True)
# print(f.get_shape())
# ==> TensorShape([Dimension(3), Dimension(4)])

(2, 3)
(4, 2)


In [11]:
from __future__ import print_function,division
import numpy as np
import tensorflow as tf

#create a Variable
w=tf.Variable(initial_value=[[1,2],[3,4]],dtype=tf.float32)
x=tf.Variable(initial_value=[[1,1],[1,1]],dtype=tf.float32)
y=tf.matmul(w,x)
z=tf.sigmoid(y)
print(z)
init_op=tf.global_variables_initializer()


with tf.Session() as session:
    session.run(init_op)
    z=session.run(z)
    print(z)

Tensor("Sigmoid:0", shape=(2, 2), dtype=float32)
[[0.95257413 0.95257413]
 [0.999089   0.999089  ]]


In [12]:
v = tf.Variable([1, 2])
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    # Usage passing the session explicitly.
    print(v.eval(sess))
    # Usage with the default session.  The 'with' block
    # above makes 'sess' the default session.
    print(v.eval())

[1 2]
[1 2]


In [14]:
# Initialize 'v' with a random tensor.
v = tf.Variable(tf.truncated_normal([10, 40]))
# Use `initialized_value` to guarantee that `v` has been
# initialized before its value is used to initialize `w`.
# The random values are picked only once.
w = tf.Variable(v.initialized_value() * 2.0)

In [15]:
from __future__ import  print_function,division
import numpy as np
import tensorflow as tf

v=tf.Variable(initial_value=[1,2])
init=tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    #显式地传递session到函数里面
    v.load(value=[3,4],session=sess)
    print(v.eval(session=sess))

[3 4]


In [16]:
from __future__ import print_function,division
import tensorflow as tf

#build graph
a=tf.constant(1.,name="a")
print("a:",a)
print("name of a:",a.name)
b=tf.constant(1.,shape=[2,2],name="b")
print("b:",b)
print("type of b:",type(b))

#construct session
sess=tf.Session()

#run in session
result_a=sess.run(a)
print("result_a:",result_a)
print("type of result_a:",type(result_a))

a: Tensor("a:0", shape=(), dtype=float32)
name of a: a:0
b: Tensor("b:0", shape=(2, 2), dtype=float32)
type of b: <class 'tensorflow.python.framework.ops.Tensor'>
result_a: 1.0
type of result_a: <class 'numpy.float32'>


In [21]:
x = tf.placeholder(tf.float32, shape=(24, 24))
import numpy as np
y = tf.matmul(x, x)

with tf.Session() as sess:
  # print(sess.run(y))  # ERROR: will fail because x was not fed.
  rand_array = np.random.rand(24, 24)
  print(sess.run(y, feed_dict={x: rand_array}))  # Will succeed.

[[ 6.255611   5.7970886  6.607641   6.4982495  6.5818825  6.0667667
   6.3986173  4.8554     7.081011   6.9581776  6.2278786  7.4192357
   4.8286767  5.6656375  6.330068   6.7661896  6.519813   5.1950736
   4.563998   8.551527   7.2255287  5.703436   5.925646   5.879561 ]
 [ 5.8394413  6.4727526  6.82571    6.0556283  5.8792453  6.434738
   5.543522   5.662057   7.309164   5.6358523  5.595095   6.4442554
   5.511141   6.671219   5.8119373  5.597594   6.28294    4.6503415
   5.0894766  7.847976   6.610932   6.9318657  4.564285   6.0612607]
 [ 5.6466293  6.3240314  7.263344   7.7690754  5.600555   7.9683757
   7.349066   5.213739   7.892042   7.112302   6.84916    7.8264546
   6.1412187  6.29309    7.0000257  6.226399   7.690059   5.428433
   6.4343657  8.167297   8.170802   7.905232   5.7970014  6.561057 ]
 [ 5.0344973  6.136187   6.917412   7.181156   4.814885   6.330578
   6.2364616  4.9186068  7.7930417  6.192325   6.2474947  6.029177
   4.7787127  5.642283   6.7212114  5.042324   6.

In [23]:
# -*- coding: utf-8 -*- 

from __future__ import print_function,division
import tensorflow as tf

#building the graph

'''
创建一个常量操作（op）产生 1x2 矩阵，这个操作（op）作为一个节点添加到默认的图中，但是这里这个矩阵并不是一个值，而是一个tensor。
创建另外一个常量操作产生一个1x2 矩阵（解释如上）
'''
mat1=tf.constant([3.,3.],name="mat1")
mat2=tf.constant([4.,4.],name="mat2")

#matrix sum.
s=tf.add(mat1,mat2)

'''
这个默认的图（grapg）现在已经有3个节点了：两个constan（）操作和一个add（）操作。为了真正的得到这个和的值，你需要把这个图投放到一个session里面执行。
'''

# Launch the default graph.
sess = tf.Session()

'''
为了得到和的值，我们要运行add 操作（op），因此我们在session里面调用“run（）”函数，把代表add op的输出结果s传到函数里面去。表明我们想从add（）操作得到输出。
'''
result=sess.run(s)
print("result:",result)

# Close the Session when we're done.
sess.close()

result: [7. 7.]


In [24]:
# -*- coding: utf-8 -*- 

from __future__ import print_function,division
import tensorflow as tf

#building the graph

#Create a Variable, that will be initialized to the scalar value 0.
state=tf.Variable(0,name="state")
print("the name of this variable:",state.name)

# Create an Op to add 1 to `state`.
one = tf.constant(1)
new_value = tf.add(state, one)
update = tf.assign(state, new_value)

# Variables must be initialized by running an `init` Op after having
# launched the graph.  We first have to add the `init` Op to the graph.
init_op = tf.initialize_all_variables()

# Launch the graph and run the ops.
with tf.Session() as sess:
  # Run the 'init' op
  sess.run(init_op)
  # Print the initial value of 'state'
  print(sess.run(state))
  # Run the op that updates 'state' and print 'state'.
  for _ in range(3):
    sess.run(update)
    print("value of state:",sess.run(state))

the name of this variable: state:0
Instructions for updating:
Use `tf.global_variables_initializer` instead.


0
value of state: 1
value of state: 2
value of state: 3


In [27]:
from __future__ import print_function,division
import tensorflow as tf

#fetch example
print("#fetch example")
a=tf.constant([1.,2.,3.],name="a")
b=tf.constant([4.,5.,6.],name="b")
c=tf.constant([0.,4.,2.],name="c")
add=a+b
mul=add*c

with tf.Session() as sess:
    result=sess.run([a,b,c,add,mul])
    print("after run:\n",result)

print("\n\n")

#feed example
print("feed example")
input1=tf.placeholder(tf.float32)
input2=tf.placeholder(tf.float32)
output=tf.matmul(input1,input2)

with tf.Session() as session:
    result_feed=session.run(output,feed_dict={input1:[2.],input2:[3.]})
    print("result:",result_feed)

#fetch example
after run:
 [array([1., 2., 3.], dtype=float32), array([4., 5., 6.], dtype=float32), array([0., 4., 2.], dtype=float32), array([5., 7., 9.], dtype=float32), array([ 0., 28., 18.], dtype=float32)]



feed example


InvalidArgumentError: In[0] and In[1] ndims must be >= 2: 1
	 [[Node: MatMul_9 = BatchMatMul[T=DT_FLOAT, adj_x=false, adj_y=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_Placeholder_14_0_0, _arg_Placeholder_15_0_1)]]

Caused by op 'MatMul_9', defined at:
  File "D:\allsoftware\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\allsoftware\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\allsoftware\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "D:\allsoftware\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "D:\allsoftware\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "D:\allsoftware\Anaconda3\lib\site-packages\zmq\eventloop\ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "D:\allsoftware\Anaconda3\lib\site-packages\tornado\ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "D:\allsoftware\Anaconda3\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "D:\allsoftware\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "D:\allsoftware\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "D:\allsoftware\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "D:\allsoftware\Anaconda3\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "D:\allsoftware\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "D:\allsoftware\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "D:\allsoftware\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "D:\allsoftware\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "D:\allsoftware\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "D:\allsoftware\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2698, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "D:\allsoftware\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2802, in run_ast_nodes
    if self.run_code(code, result):
  File "D:\allsoftware\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-27-13f822d0a011>", line 22, in <module>
    output=tf.matmul(input1,input2)
  File "D:\allsoftware\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1976, in matmul
    a, b, adj_x=adjoint_a, adj_y=adjoint_b, name=name)
  File "D:\allsoftware\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 1295, in batch_mat_mul
    "BatchMatMul", x=x, y=y, adj_x=adj_x, adj_y=adj_y, name=name)
  File "D:\allsoftware\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "D:\allsoftware\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3414, in create_op
    op_def=op_def)
  File "D:\allsoftware\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): In[0] and In[1] ndims must be >= 2: 1
	 [[Node: MatMul_9 = BatchMatMul[T=DT_FLOAT, adj_x=false, adj_y=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_Placeholder_14_0_0, _arg_Placeholder_15_0_1)]]
